
guard 'minitest' do
  watch(%r|^test/(.*)_test\.rb|)
  watch(%r|^app/(.*?)([^/\\]+)\.rb|)     { |m| "test/#{m[1]}#{m[2]}_test.rb" }
  watch(%r|app.rb|)     { |m| "test" }
  watch(%r|^test/helper\.rb|)         { "test" }
end
